version: '3'
services:
  backend:
    build: .
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=development
      - PORT=5000
    volumes:
      - .:/app
    networks:
      - app-network
networks:
  app-network:
    driver: bridge
